name: 'setupJDK'
description: 'setupJDK.'
inputs:
   distribution:
     required: true
   java-version: 
     required: true
runs:
  using: "composite"
  steps:
   - name: Checkout
     uses: actions/checkout@v2
     with:
        path: ${{ github.repository }}
        fetch-depth: 0
   - uses: actions/setup-java@v3
     with:
      distribution: ${{ inputs.distribution }}
      java-version: ${{ inputs.java-version }}
