name: Branch_Check
on: 
  push:
   branches:
   - '*'
  
jobs:
 
  delete-branch:
   
    runs-on: ubuntu-latest
    steps:

     - name: branch check
       run: |
         #!/bin/bash
         patterns=("bugfix-" "release-" "hotfix-" "defect-de" "feature-*" "pr")
         name=${{ github.ref }}
         echo ${{ github.ref }}
         for pattern in "${patterns[@]}"
          do
          if [[ $name =~ $pattern ]]; then
          echo "The string is matches the pattern: $pattern"
          else
            echo "The string is not matches the pattern: $pattern"
            fi
            done
       shell: bash
