name: Branch_Check
on: 
  push:
   branches:
   - '*'
  
jobs:
 
  delete-branch:
   
    runs-on: ubuntu-latest
    steps:

     - name: branch check
       run: |
          echo ${{github.ref}}
          name=${{github.ref}} 
          if [[ "${name}" != @(bugfix-*|release-*|hotfix-*|defect-de*|feature-*|Pr*) ]]; then
          echo " Branch pattern not matching"
          else
          echo " Branch pattern is matchin"
       shell: bash
