name: Deploy Devl
on:
  workflow_dispatch:
    inputs:
      scenarios:
        type: string
        description: File Name of Scenarios to be tested
      user_simulations:
        type: string
        description: File Name of user simulation params
      feeder:
        type: string
        description: File Name of csv feeder which is to be feeded

env: 
  project_name: fdssf"
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: deploymetn
      run: |
          echo "### inputs" >> $GITHUB_STEP_SUMMARY
          echo "- scenarios: ${{ inputs.scenarios}}" >> $GITHUB_STEP_SUMMARY
          echo "- user_simulations: ${{ inputs.user_simulations}}" >> $GITHUB_STEP_SUMMARY
          echo "- feeder: ${{ inputs.feeder}}" >> $GITHUB_STEP_SUMMARY
          echo "Printing scenarios ${{ github.event.inputs.scenarios }}"  
          echo "Printing user_simulations ${{ github.event.inputs.user_simulations }}"
          echo "Printing feeder ${{ github.event.inputs.feeder }}"
