name: delete_branch
on: 
  pull_request:
    types: [closed]

  
jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
      - name: delete branch
        if: github.event.pull_request.merged == true
        uses: Suresh051/delete-merged-branch@main
        env:
           GITHUB_TOKEN: ${{ github.token }}
