name: java-version
on:
  workflow_dispatch:
  workflow_call:
    
jobs:
  reponame:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: setup JDK
       uses: ./.github/actions/setupJDK@mater
       with: 
          distribution: 'temurin'
          java-version: '8'
     - run: |
           java -version
