name: reponame
on: 
  push:
   branches:
    - '*'
jobs:
  reponame:
   runs-on: ubuntu-latest
   steps:
     - name: setup JDK
       uses: Github-Repo/.github/workflows/setupJDK@master
       with: 
          distribution: temurin
          java-version: 8
     - run: |
           java -version
      #- run: echo ::set-env name=GITHUB_REPO_NAME::${GITHUB_REPOSITORY#*/}
     - run: echo ${{env.GITHUB_REPO_NAME}}
