name: java-version
on: 
  push:
   branches:
    - '*'
jobs:
  reponame:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/setup-java@v2
     - name: setup JDK
       uses: ./.github/workflows/setupJDK@master
       with: 
          distribution: 'temurin'
          java-version: '8'
     - run: |
           java -version
      #- run: echo ::set-env name=GITHUB_REPO_NAME::${GITHUB_REPOSITORY#*/}
     - run: echo ${{env.GITHUB_REPO_NAME}}
