name: java-version-prod
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["dev.yml"]
    types:
      - completed
jobs:
  reponame:
   runs-on: ubuntu-latest
   steps:
     - uses: suresh051/Github-Repo/.github/worflows/devl.yml@master
     - uses: actions/checkout@v2
     - name: setup JDK
       run: echo "prod"
           
