name: java-version-prod
on:
  workflow_dispatch:
jobs:
  reponame:
   runs-on: ubuntu-latest
   steps:
     - uses: ./github/worflows/devl.yml@master
     - uses: actions/checkout@v2
     - name: setup JDK
       run: echo "prod"
           
