name: readfile
on:
  push:
   branches:
    - master
jobs:
  branch_check:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
   - run : |
         #!/bin/bash
         
         touch scenario.txt
         ls -lrt
         "find ./src/it/resources/scenarios -type f -exec basename {} \\; >> scenario.txt"
     shell: bash
   - name: Read readme
     id: package
     uses: juliangruber/read-file-action@v1
     with:
      path: ./scenario.txt
   - name: Echo package.json
     run: echo "${{ steps.package.outputs.content }}"
