name: readfile
on:
  push:
   branches:
    - master
jobs:
  branch_check:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3
   - name: Read readme
     id: package
     uses: juliangruber/read-file-action@v1
     with:
      path: ./.github/workflows/readme
   - name: Echo package.json
     run: echo "${{ steps.package.outputs.content }}"
