name: reponame
on: 
  push:
   branches:
    - '*'
jobs:
  reponame:
   runs-on: ubuntu-latest 
   steps:
    - run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
    - run: |
       echo ${{env.REPOSITORY_NAME}}
     

