name: reponame
on: 
  push:
  branches:
  - '*'
jobs:
  reponame:
   env: 
   GITHUB_REPO_NAME: ${{ GITHUB_REPOSITORY#*/ }}
    runs-on: ubuntu-latest
    steps:
      #- run: echo ::set-env name=GITHUB_REPO_NAME::${GITHUB_REPOSITORY#*/}
       - run: echo ${{env.GITHUB_REPO_NAME}}
