name: reponame
on: 
  push:
   branches:
    - '*'
jobs:
  reponame:
   runs-on: ubuntu-latest 
   steps:
    - name: Set env
      run: echo "GITHUB_REPO_NAME=$(echo $GITHUB_REPOSITORY#*/)" >> $GITHUB_ENV
    - name: Test
      run: echo $GITHUB_REPO_NAME
