name: reponame
on: 
  push:
   branches:
    - '*'
jobs:
  reponame:
   runs-on: ubuntu-latest 
   steps:
    - name: Test
      run: echo $GITHUB_REPO_NAME
  reponame1:
   runs-on: ubuntu-latest 
   needs: [reponame]
   steps:
    - name: Test
      run: echo $GITHUB_REPO_NAME
  reponame2:
   runs-on: ubuntu-latest 
   needs: [reponame1]
   steps:
    - name: Test
      run: echo $GITHUB_REPO_NAME
